import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  gridOverlay: {
    opacity: 0.05,
    backgroundColor: '#FAFAFA',
  },
  leftColumn: {
    position: 'absolute',
    left: 24,
    top: 90,
    bottom: 280,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    zIndex: 10,
  },
  leftAlignText: {
    fontFamily: 'monospace',
    fontSize: 10,
    fontWeight: '800',
    color: '#333',
    letterSpacing: 1,
    lineHeight: 14,
  },
  timeText: {
    fontFamily: 'monospace',
    fontSize: 26,
    color: '#000',
    letterSpacing: 2,
  },
  earthIconContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 30,
    width: 40,
    height: 40,
    position: 'relative',
  },
  staticEarthLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  animatedEarthLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  centerColumn: {
    flex: 0.9,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 40,
  },
  circularImageWrapper: {
    width: 110,
    height: 110,
    borderRadius: 55,
    overflow: 'hidden',
    backgroundColor: '#DDD',
  },
  rightTopPill: {
    position: 'absolute',
    right: 20,
    width: 60,
    backgroundColor: '#000',
    borderRadius: 40,
    zIndex: 10,
    overflow: 'hidden',
  },
  pillAvatarContainer: {
    position: 'absolute',
    top: 10,
    alignSelf: 'center',
  },
  pillAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#FFF',
  },
  pillTextContainer: {
    position: 'absolute',
    top: '40%',
    width: '100%',
    alignItems: 'center',
    transform: [{ translateY: -6 }],
  },
  pillName: {
    color: '#FFF',
    fontSize: 9,
    fontFamily: 'monospace',
    fontWeight: '700',
  },
  whiteCircleContainer: {
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blackCircle: {
    width: 22,
    height: 22,
    borderRadius: 11, 
    backgroundColor: '#000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rightEdgeMenu: {
    position: 'absolute',
    bottom: 150,
    right: 0,
    width: 60,
    height: 260,
    zIndex: 10,
  },
  menuIconsContainer: {
    position: 'absolute',
    top: 124,
    right: 10, 
    alignItems: 'center',
    gap: 18,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 40,
    left: 24,
    right: 24,
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 10,
  },
  hamburger: {
    width: 18,
    gap: 4,
  },
  hamburgerLine: {
    width: '100%',
    height: 2,
    backgroundColor: '#000',
  },
  exploreText: {
    fontFamily: 'monospace',
    fontSize: 9,
    fontWeight: '800',
    marginLeft: 15,
    letterSpacing: 1,
    color: '#000',
  },
  scrubber: {
    flex: 1,
    height: 20,
    justifyContent: 'center',
    marginHorizontal: 15,
  },
  scrubberLine: {
    width: '100%',
    height: 1.5,
    backgroundColor: '#000',
  },
  scrubberHandle: {
    position: 'absolute',
    width: 2,
    height: 12,
    backgroundColor: '#000',
    left: '30%', 
  },
  imageCover:{
     width: '100%',
     height: '100%'
  },
});